version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx 
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
      - db

  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=timekeeping
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    environment:
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
  
  app: 
    container_name: app
    build: ./docker
    volumes:
      - ./src/:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
